name: Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: knowledgeboxacr
  CONTAINER_APP_NAME: knowledge-box-structure-service
  RESOURCE_GROUP: knowledge-box-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure CLI Extensions
        run: |
          az extension add --name containerapp --upgrade --yes --allow-preview

      - name: Get ACR Credentials
        id: acr-creds
        run: |
          echo "Using ACR: ${{ env.AZURE_CONTAINER_REGISTRY }}"
          ACR_USERNAME=$(az acr credential show -n "${{ env.AZURE_CONTAINER_REGISTRY }}" --query username -o tsv)
          ACR_PASSWORD=$(az acr credential show -n "${{ env.AZURE_CONTAINER_REGISTRY }}" --query passwords[0].value -o tsv)
          echo "::add-mask::$ACR_PASSWORD"
          echo "username=$ACR_USERNAME" >> $GITHUB_OUTPUT
          echo "password<<EOF" >> $GITHUB_OUTPUT
          echo "$ACR_PASSWORD" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ steps.acr-creds.outputs.username }}
          password: ${{ steps.acr-creds.outputs.password }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "./src"
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
          cache-from: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:buildcache,mode=max
          cache-to: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:buildcache,mode=max

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:latest
          acrUsername: ${{ steps.acr-creds.outputs.username }}
          acrPassword: ${{ steps.acr-creds.outputs.password }}
          # All secrets are managed by Terraform and accessed by the app via its managed identity
